version: '3.4'

networks:
  auth-service:
  
services:
  authenticationservice:
    container_name: authenticationservice
    hostname: authentication.localdev.com
    image: authenticationservice
    build:
      context: .
      dockerfile: src/poc.auth.service/Dockerfile
    restart: unless-stopped
    ports:
      - "8855:8855"
    volumes:
      - ./src/poc.auth.service/:/https/:ro
      # - ./src/poc.auth.service/localCA.crt:/usr/local/share/ca-certificates/:ro
    networks:
      - auth-service
    environment:
      - ASPNETCORE_URLS=https://+:8855
      - ASPNETCORE_HTTPS_PORT=8855
      - ASPNETCORE_Kestrel__Certificates__Default__Password=hello
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localdev.com.pfx